// Generates config.js from environment variable MY_API_KEY.
// Loads .env.local or .env for local dev via dotenv, or uses env set by CI.

const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load environment from .env.local if present, else .env
const envPathLocal = path.join(process.cwd(), '.env.local');
const envPathDefault = path.join(process.cwd(), '.env');
if (fs.existsSync(envPathLocal)) {
  dotenv.config({ path: envPathLocal });
} else if (fs.existsSync(envPathDefault)) {
  dotenv.config({ path: envPathDefault });
}

const apiKey = process.env.MY_API_KEY;
if (!apiKey) {
  console.error('Missing MY_API_KEY environment variable.');
  process.exit(1);
}

const output = `// Auto-generated by scripts/generate-config.js\nexport const API_KEY = '${apiKey}';\n`;
const outPath = path.join(process.cwd(), 'config.js');
fs.writeFileSync(outPath, output, { encoding: 'utf8' });
console.log('config.js generated successfully');
