// Generates config.js from environment variable API_KEY.
// Loads .env.local or .env for local dev (no external deps required).

const fs = require('fs');
const path = require('path');

const parseEnvFile = (filePath) => {
  const content = fs.readFileSync(filePath, { encoding: 'utf8' });
  const lines = content.split(/\r?\n/);
  lines.forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) return;
    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!process.env[key]) {
      process.env[key] = value;
    }
  });
};

// Load environment from .env.local if present, else .env
const envPathLocal = path.join(process.cwd(), '.env.local');
const envPathDefault = path.join(process.cwd(), '.env');
if (fs.existsSync(envPathLocal)) {
  parseEnvFile(envPathLocal);
} else if (fs.existsSync(envPathDefault)) {
  parseEnvFile(envPathDefault);
}

const apiKey = process.env.API_KEY;
if (!apiKey) {
  console.error('Missing API_KEY environment variable.');
  process.exit(1);
}

const output = `// Auto-generated by scripts/generate-config.js\nwindow.API_KEY = '${apiKey}';\n`;
const outPath = path.join(process.cwd(), 'config.js');
fs.writeFileSync(outPath, output, { encoding: 'utf8' });
console.log('config.js generated successfully');
